FROM arm32v7/ubuntu:latest

MAINTAINER cade <cade.call@mediciventures.com>

EXPOSE $RPCPORT

EXPOSE $PORT

RUN useradd -ms /bin/bash raianetwork

RUN mkdir /etc/raianetwork

RUN mkdir /var/lib/raianetwork

RUN chown raianetwork:raianetwork /etc/raianetwork /var/lib/raianetwork

WORKDIR /home/raianetwork

COPY --chown=raianetwork:raianetwork linux64/* ./run.sh /home/raianetwork/

USER raianetwork

CMD ["/home/raianetwork/run.sh"]
